atom_types = [
    'N', 'CA', 'C', 'CB', 'O', 'CG', 'CG1', 'CG2', 'OG', 'OG1', 'SG', 'CD',
    'CD1', 'CD2', 'ND1', 'ND2', 'OD1', 'OD2', 'SD', 'CE', 'CE1', 'CE2', 'CE3',
    'NE', 'NE1', 'NE2', 'OE1', 'OE2', 'CH2', 'NH1', 'NH2', 'OH', 'CZ', 'CZ2',
    'CZ3', 'NZ', 'OXT'
]

RES_ATOMS_DICT = {
    "ALA": {"N": 0, "CA": 1, "C": 2, "O": 3, "CB": 4, "OXT": 5},
    "ARG": {
        "N": 0,
        "CA": 1,
        "C": 2,
        "O": 3,
        "CB": 4,
        "CG": 5,
        "CD": 6,
        "NE": 7,
        "CZ": 8,
        "NH1": 9,
        "NH2": 10,
        "OXT": 11,
    },
    "ASN": {
        "N": 0,
        "CA": 1,
        "C": 2,
        "O": 3,
        "CB": 4,
        "CG": 5,
        "OD1": 6,
        "ND2": 7,
        "OXT": 8,
    },
    "ASP": {
        "N": 0,
        "CA": 1,
        "C": 2,
        "O": 3,
        "CB": 4,
        "CG": 5,
        "OD1": 6,
        "OD2": 7,
        "OXT": 8,
    },
    "CYS": {"N": 0, "CA": 1, "C": 2, "O": 3, "CB": 4, "SG": 5, "OXT": 6},
    "GLN": {
        "N": 0,
        "CA": 1,
        "C": 2,
        "O": 3,
        "CB": 4,
        "CG": 5,
        "CD": 6,
        "OE1": 7,
        "NE2": 8,
        "OXT": 9,
    },
    "GLU": {
        "N": 0,
        "CA": 1,
        "C": 2,
        "O": 3,
        "CB": 4,
        "CG": 5,
        "CD": 6,
        "OE1": 7,
        "OE2": 8,
        "OXT": 9,
    },
    "GLY": {"N": 0, "CA": 1, "C": 2, "O": 3, "OXT": 4},
    "HIS": {
        "N": 0,
        "CA": 1,
        "C": 2,
        "O": 3,
        "CB": 4,
        "CG": 5,
        "ND1": 6,
        "CD2": 7,
        "CE1": 8,
        "NE2": 9,
        "OXT": 10,
    },
    "ILE": {
        "N": 0,
        "CA": 1,
        "C": 2,
        "O": 3,
        "CB": 4,
        "CG1": 5,
        "CG2": 6,
        "CD1": 7,
        "OXT": 8,
    },
    "LEU": {
        "N": 0,
        "CA": 1,
        "C": 2,
        "O": 3,
        "CB": 4,
        "CG": 5,
        "CD1": 6,
        "CD2": 7,
        "OXT": 8,
    },
    "LYS": {
        "N": 0,
        "CA": 1,
        "C": 2,
        "O": 3,
        "CB": 4,
        "CG": 5,
        "CD": 6,
        "CE": 7,
        "NZ": 8,
        "OXT": 9,
    },
    "MET": {
        "N": 0,
        "CA": 1,
        "C": 2,
        "O": 3,
        "CB": 4,
        "CG": 5,
        "SD": 6,
        "CE": 7,
        "OXT": 8,
    },
    "PHE": {
        "N": 0,
        "CA": 1,
        "C": 2,
        "O": 3,
        "CB": 4,
        "CG": 5,
        "CD1": 6,
        "CD2": 7,
        "CE1": 8,
        "CE2": 9,
        "CZ": 10,
        "OXT": 11,
    },
    "PRO": {"N": 0, "CA": 1, "C": 2, "O": 3, "CB": 4, "CG": 5, "CD": 6, "OXT": 7},
    "SER": {"N": 0, "CA": 1, "C": 2, "O": 3, "CB": 4, "OG": 5, "OXT": 6},
    "THR": {"N": 0, "CA": 1, "C": 2, "O": 3, "CB": 4, "OG1": 5, "CG2": 6, "OXT": 7},
    "TRP": {
        "N": 0,
        "CA": 1,
        "C": 2,
        "O": 3,
        "CB": 4,
        "CG": 5,
        "CD1": 6,
        "CD2": 7,
        "NE1": 8,
        "CE2": 9,
        "CE3": 10,
        "CZ2": 11,
        "CZ3": 12,
        "CH2": 13,
        "OXT": 14,
    },
    "TYR": {
        "N": 0,
        "CA": 1,
        "C": 2,
        "O": 3,
        "CB": 4,
        "CG": 5,
        "CD1": 6,
        "CD2": 7,
        "CE1": 8,
        "CE2": 9,
        "CZ": 10,
        "OH": 11,
        "OXT": 12,
    },
    "VAL": {"N": 0, "CA": 1, "C": 2, "O": 3, "CB": 4, "CG1": 5, "CG2": 6, "OXT": 7},
    "UNK": {"N": 0, "CA": 1, "C": 2, "O": 3, "CB": 4, "CG": 5, "OXT": 6},
}

ELEMENT_MAPPING = {
    'H': 1, 'HE': 2, 'LI': 3, 'BE': 4, 'B': 5, 'C': 6, 'N': 7, 'O': 8, 'F': 9, 'NE': 10,
    'NA': 11, 'MG': 12, 'AL': 13, 'SI': 14, 'P': 15, 'S': 16,
}

restype_1to3 = {
    'A': 'ALA',
    'R': 'ARG',
    'N': 'ASN',
    'D': 'ASP',
    'C': 'CYS',
    'Q': 'GLN',
    'E': 'GLU',
    'G': 'GLY',
    'H': 'HIS',
    'I': 'ILE',
    'L': 'LEU',
    'K': 'LYS',
    'M': 'MET',
    'F': 'PHE',
    'P': 'PRO',
    'S': 'SER',
    'T': 'THR',
    'W': 'TRP',
    'Y': 'TYR',
    'V': 'VAL',
    'X': 'UNK',  # Unknown residue type
}

restype_idx21 = {idx: res for idx, res in enumerate(restype_1to3.keys())}